name: PvPToggle
main: com.sleelin.pvptoggle.PvPToggle
version: 0.2
commands:
    pvp:
        description: Toggles whether player can take damage from another player
        uasge: |
            /pvp [on|off|enable|disable]
    gpvp:
        description: Toggles global pvp status
        uasge: |
            /gpvp [on|off|enable|disable]
